import 'dart:convert';
import 'dart:io';

const _outputPath = 'skills/rudi-ui-building/references/public-api.md';

void main(List<String> arguments) {
  final unknownArguments = arguments.where((argument) => argument != '--check');
  if (unknownArguments.isNotEmpty) {
    stderr.writeln(
      'Usage: dart run tool/generate_skill_reference.dart [--check]',
    );
    exitCode = 64;
    return;
  }

  final generated = _generateReference();
  final output = File(_outputPath);
  if (arguments.contains('--check')) {
    if (!output.existsSync() ||
        _normalizeText(output.readAsStringSync()) != generated) {
      stderr.writeln(
        '$_outputPath is stale. Run '
        '`dart run tool/generate_skill_reference.dart`.',
      );
      exitCode = 1;
    }
    return;
  }

  output.parent.createSync(recursive: true);
  output.writeAsStringSync(generated);
  stdout.writeln('Updated $_outputPath.');
}

String _generateReference() {
  final pubspec = File('pubspec.yaml').readAsStringSync();
  final version = RegExp(
    r'^version:\s*([^\s]+)',
    multiLine: true,
  ).firstMatch(pubspec)?.group(1);
  if (version == null) {
    throw const FormatException('Could not read the package version.');
  }

  final barrel = File('lib/rudi_ui.dart').readAsStringSync();
  final exports = RegExp(
    r"^export\s+'([^']+)';",
    multiLine: true,
  ).allMatches(barrel).map((match) => match.group(1)!).toList();
  if (exports.isEmpty) {
    throw const FormatException('No public exports found in lib/rudi_ui.dart.');
  }

  final sourcePaths = <String>{
    'CHANGELOG.md',
    'README.md',
    'example/lib/main.dart',
    'lib/rudi_ui.dart',
    for (final export in exports) 'lib/$export',
  }.toList()..sort();
  final sourceFingerprint = _fingerprint(sourcePaths);

  final buffer = StringBuffer()
    ..writeln('# Rudi UI public API')
    ..writeln()
    ..writeln(
      '<!-- Generated by tool/generate_skill_reference.dart. Do not edit. -->',
    )
    ..writeln()
    ..writeln('Package version: `$version`')
    ..writeln()
    ..writeln('Source fingerprint: `$sourceFingerprint`')
    ..writeln()
    ..writeln(
      'This catalog lists the public top-level declarations exported by '
      '`package:rudi_ui/rudi_ui.dart`. Use it for discovery, then inspect the '
      'resolved package source for exact parameters and current behavior.',
    );

  for (final export in exports) {
    final sourcePath = 'lib/$export';
    final source = File(sourcePath);
    if (!source.existsSync()) {
      throw FileSystemException('Exported source does not exist', sourcePath);
    }
    final symbols = _extractSymbols(source.readAsStringSync());
    if (symbols.isEmpty) {
      throw FormatException(
        'No documented public declarations in $sourcePath.',
      );
    }

    buffer
      ..writeln()
      ..writeln('## `$sourcePath`')
      ..writeln();
    for (final symbol in symbols) {
      buffer.writeln('- `${symbol.name}` — ${symbol.summary}');
    }
  }

  return buffer.toString();
}

String _fingerprint(List<String> paths) {
  var hash = BigInt.parse('cbf29ce484222325', radix: 16);
  final prime = BigInt.parse('100000001b3', radix: 16);
  final mask = BigInt.parse('ffffffffffffffff', radix: 16);
  for (final path in paths) {
    final file = File(path);
    if (!file.existsSync()) {
      throw FileSystemException('Fingerprint input does not exist', path);
    }
    final content = _normalizeText(file.readAsStringSync());
    final bytes = utf8.encode('$path\u0000$content\u0000');
    for (final byte in bytes) {
      hash ^= BigInt.from(byte);
      hash = (hash * prime) & mask;
    }
  }
  return hash.toRadixString(16).padLeft(16, '0');
}

String _normalizeText(String value) {
  return value.replaceAll('\r\n', '\n').replaceAll('\r', '\n');
}

List<_Symbol> _extractSymbols(String source) {
  final normalized = _normalizeText(source);
  final documentedDeclaration = RegExp(
    r'((?:^///[^\n]*(?:\n|$))+)(?:^@[^\n]*(?:\n|$))*^([^\n]+)',
    multiLine: true,
  );
  final symbols = <_Symbol>[];

  for (final match in documentedDeclaration.allMatches(normalized)) {
    final declaration = match.group(2)!.trim();
    final name = _declarationName(declaration);
    if (name == null || name.startsWith('_')) continue;

    final summary = match
        .group(1)!
        .split('\n')
        .map((line) => line.replaceFirst(RegExp(r'^///\s?'), '').trim())
        .where((line) => line.isNotEmpty)
        .join(' ')
        .replaceAllMapped(
          RegExp(r'\[([A-Za-z][A-Za-z0-9_.]*)\](?!\()'),
          (match) => '`${match.group(1)}`',
        );
    symbols.add(_Symbol(name, summary));
  }
  return symbols;
}

String? _declarationName(String declaration) {
  final type = RegExp(
    r'^(?:(?:abstract|base|final|interface|sealed)\s+)*'
    r'class(?:\s+const)?\s+([A-Za-z][A-Za-z0-9_]*)'
    r'|^enum\s+([A-Za-z][A-Za-z0-9_]*)'
    r'|^typedef\s+([A-Za-z][A-Za-z0-9_]*)'
    r'|^extension\s+([A-Za-z][A-Za-z0-9_]*)',
  ).firstMatch(declaration);
  if (type != null) {
    for (var group = 1; group <= 4; group++) {
      final name = type.group(group);
      if (name != null) return name;
    }
  }

  return RegExp(r'\b(showRudi[A-Za-z0-9_]*)\s*(?:<[^>]+>)?\s*\(')
      .firstMatch(declaration)
      ?.group(1);
}

final class _Symbol {
  const _Symbol(this.name, this.summary);

  final String name;
  final String summary;
}
